<div class="navbar navbar-fixed-top navbar-inverse">
    <div class="navbar-inner">
        <div class="container-fluid">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <?php if ($this->brand): ?>
                <a class="brand" href="<?php echo $this->escapeHtmlAttr($this->brand->getHref()) ?>">
                    <?php if (isset($this->brand->icon)): ?>
                        <i class="icon-<?php echo $this->escapeHtmlAttr($this->brand->icon) ?> icon-white"></i>
                    <?php endif ?>
                    <?php echo $this->escapeHtml($this->brand->getLabel()) ?>
                </a>
            <?php endif ?>
            <?php if ($this->container): ?>
                <div class="nav-collapse collapse">
                    <?php if ($this->container->hasPages()): ?>
                        <ul class="nav">
                            <?php
                            foreach ($this->container->getPages() as $page):
                                $liClass   = null;
                                $liClasses = array();
                                if ($page->isActive) {
                                    $liClasses[] = 'active';
                                }
                                if ($page->hasPages()) {
                                    $liClasses[] = 'dropdown';
                                }
                                if (count($liClasses) > 0) {
                                    $liClass = ' class="' . implode(' ', $liClasses) . '"';
                                }
                                ?>
                                <li<?php echo $liClass ?>>
                                    <a href="<?php echo $this->escapeHtmlAttr($page->getHref()) ?>"
                                    <?php echo $page->hasPages() ? 'class="dropdown-toggle" data-toggle="dropdown"' : null ?>
                                       >
                                           <?php if (isset($page->icon)): ?>
                                            <i class="icon-white icon-<?php echo $this->escapeHtmlAttr($page->icon) ?>"></i>
                                        <?php endif ?>
                                        <?php echo $this->escapeHtml($page->getLabel()) ?>
                                        <?php if ($page->hasPages()): ?>
                                            <b class="caret"></b>
                                        <?php endif ?>
                                    </a>
                                    <?php if ($page->hasPages()): ?>
                                        <ul class="dropdown-menu">
                                            <?php foreach ($page->getPages() as $subPage): ?>
                                                <li<?php $subPage->isActive() ? ' class="active"' : null ?>>
                                                    <a href="<?php echo $this->escapeHtmlAttr($subPage->getHref()) ?>">
                                                        <?php echo $this->escapeHtml($subPage->getLabel()) ?>
                                                    </a>
                                                </li>
                                            <?php endforeach ?>
                                        </ul>
                                    <?php endif ?>
                                </li>
                                <?php
                            endforeach
                            ?>
                        </ul>
                    <?php endif ?>
                </div>
            <?php endif ?>
        </div>
    </div>
</div>