<?php echo $this->doctype() ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle() ?>
        <?php echo $this->headMeta() ?>
        <?php echo $this->headLink() ?>
        <?php echo $this->headScript() ?>
    </head>
    <body>
        <?php echo $this->navigation('navigation')->bar() ?>
        <div class="container-fluid">
            <?php echo $this->messages() ?>
            <div class="row-fluid">
                <?php echo $this->content ?>
            </div>
        </div>
        <?php echo $this->inlineScript() ?>
    </body>
</html>